services:
  frontend:
    container_name: vue3
    build:
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /var/www/frontend
    environment:
      - PATH=./node_modules/.bin:$PATH
    volumes:
      - ../vue-test:/var/www/frontend
    command: sh -c 'pnpm install && pnpm run dev --host 0.0.0.0'